import { ExternalLink, Plus, Search, Trash2 } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { api } from "../api/tauri";
import { PageHeader } from "../components/ui/PageHeader";
import type { GlossaryTerm, WikipediaCandidate } from "../types/domain";

const empty=():GlossaryTerm=>({id:0,term:"",canonicalName:"",aliases:[],definition:"",source:"manual",sourceTitle:"",sourceUrl:"",wikipediaSnapshot:"",status:"confirmed",updatedAt:0});
export function Glossary(){
 const [items,setItems]=useState<GlossaryTerm[]>([]),[editing,setEditing]=useState<GlossaryTerm>(empty()),[query,setQuery]=useState(""),[candidates,setCandidates]=useState<WikipediaCandidate[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const termInputRef=useRef<HTMLInputElement>(null);
 const load=()=>api.glossaryTerms(query).then(setItems).catch(reason=>setError(String(reason)));
 useEffect(()=>{void load()},[query]);
 function create(){setEditing(empty());setCandidates([]);setError("");requestAnimationFrame(()=>termInputRef.current?.focus())}
 async function wiki(){if(!editing.term.trim())return;setBusy(true);setError("");try{setCandidates(await api.searchWikipedia(editing.term.trim()))}catch(reason){setError(String(reason))}finally{setBusy(false)}}
 function choose(item:WikipediaCandidate){const definition=[item.description,item.excerpt].filter(Boolean).join("。 ");setEditing(value=>({...value,canonicalName:item.title,definition,source:"wikipedia",sourceTitle:item.title,sourceUrl:item.url,wikipediaSnapshot:definition,status:"confirmed"}));setCandidates([])}
 async function save(){setBusy(true);setError("");try{const savedTerm=editing.term.trim();await api.saveGlossaryTerm({...editing,term:savedTerm,canonicalName:editing.canonicalName||savedTerm});const refreshed=await api.glossaryTerms(query);setItems(refreshed);setEditing(refreshed.find(item=>item.term===savedTerm)??empty());setCandidates([])}catch(reason){setError(String(reason))}finally{setBusy(false)}}
 async function remove(id:number){await api.deleteGlossaryTerm(id);if(editing.id===id)setEditing(empty());await load()}
 return <><PageHeader title="名词库" subtitle="维基百科负责初始化，人工编辑内容优先生效；解释只作为 AI 背景。" actions={<button className="button button--primary" onClick={create}><Plus size={15}/>新建名词</button>}/><div className="glossary-layout"><section className="glossary-list"><label className="field field--search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索名词或解释"/></label><div className="glossary-table-wrap"><table className="glossary-table"><thead><tr><th>名词</th><th>来源</th><th>状态</th></tr></thead><tbody>{items.map(item=><tr key={item.id} className={editing.id===item.id?"active":""} onClick={()=>{setEditing(item);setCandidates([]);setError("")}}><td><strong>{item.term}</strong><small>{item.definition.slice(0,45)}</small></td><td>{item.source==="wikipedia"?"维基百科":"人工编辑"}</td><td><span>{item.status==="confirmed"?"已确认":"待确认"}</span></td></tr>)}</tbody></table>{items.length===0&&<div className="glossary-empty">暂无名词</div>}</div></section><section className="glossary-editor"><header className="glossary-editor__header"><strong>{editing.id>0?"编辑名词":"新建名词"}</strong><span>{editing.id>0?"修改后保存将立即用于 AI 问答":"填写名词后可优先从维基百科获取解释"}</span></header><label>名词<input ref={termInputRef} value={editing.term} onChange={e=>setEditing({...editing,term:e.target.value})} placeholder="输入需要解释的名词"/></label><label>标准名称<input value={editing.canonicalName} onChange={e=>setEditing({...editing,canonicalName:e.target.value})}/></label><label>别名<input value={editing.aliases.join("、")} onChange={e=>setEditing({...editing,aliases:e.target.value.split(/[、,，]/).map(x=>x.trim()).filter(Boolean)})}/></label><div className="glossary-wiki"><button disabled={busy||!editing.term.trim()} onClick={()=>void wiki()}><Search size={14}/>{busy?"正在搜索…":"优先从维基百科获取"}</button>{editing.sourceUrl&&<button onClick={()=>void api.openExternalUrl(editing.sourceUrl)}><ExternalLink size={14}/>查看来源</button>}</div>{candidates.length>0&&<div className="glossary-candidates">{candidates.map(item=><button key={item.title} onClick={()=>choose(item)}><strong>{item.title}</strong><span>{item.description||item.excerpt}</span></button>)}</div>}<label>解释<textarea rows={10} value={editing.definition} onChange={e=>setEditing({...editing,definition:e.target.value,source:"manual"})}/></label>{error&&<p className="glossary-error">{error}</p>}<footer>{editing.id>0&&<button className="danger" onClick={()=>void remove(editing.id)}><Trash2 size={14}/>删除</button>}<button className="button button--primary" disabled={busy||!editing.term.trim()||!editing.definition.trim()} onClick={()=>void save()}>保存并确认</button></footer></section></div></>;
}
