import { Check, Eye, EyeOff } from "lucide-react";
import { useEffect, useState } from "react";
import { api } from "../api/tauri";
import { Button } from "../components/ui/Button";
import { PageHeader } from "../components/ui/PageHeader";
function SecretField({label,kind}:{label:string;kind:string}){const [value,setValue]=useState("");const [show,setShow]=useState(false);const [status,setStatus]=useState<"idle"|"testing"|"success"|"error">("idle");const [message,setMessage]=useState("");async function test(){setStatus("testing");setMessage("");try{await api.saveSecret(kind,value);await api.testConnection(kind);setStatus("success")}catch(error){setStatus("error");setMessage(typeof error==="string"?error:error instanceof Error?error.message:"连接失败")}}return <div className="setting-field"><label>{label}</label><div className="secret-input"><input type={show?"text":"password"} placeholder="输入 API Key" value={value} onChange={e=>{setValue(e.target.value);setStatus("idle")}}/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff size={16}/>:<Eye size={16}/>}</button></div><Button variant="secondary" onClick={test} disabled={!value||status==="testing"}>{status==="success"?<><Check size={15}/>连接成功</>:status==="testing"?"正在连接…":"测试连接"}</Button>{status==="error"&&<small className="field-error">{message}</small>}</div>}
function AiSettings(){const [provider,setProvider]=useState("DeepSeek");const [endpoint,setEndpoint]=useState("");const [model,setModel]=useState("");const [apiKey,setApiKey]=useState("");const [status,setStatus]=useState<"idle"|"testing"|"success"|"error">("idle");const [message,setMessage]=useState("");useEffect(()=>{api.aiSettings().then(value=>{if(value){setProvider(value.provider);setEndpoint(value.endpoint);setModel(value.model)}})},[]);async function saveAndTest(){setStatus("testing");setMessage("");try{await api.saveAiSettings({provider,endpoint,model},apiKey);await api.testAi();setStatus("success")}catch(error){setStatus("error");setMessage(typeof error==="string"?error:error instanceof Error?error.message:"AI 连接失败")}}return <div className="setting-field"><label>Provider</label><select value={provider} onChange={e=>setProvider(e.target.value)}><option>DeepSeek</option><option>MiniMax</option><option>自定义</option></select><label>Chat Completions Endpoint</label><input className="settings-input" value={endpoint} onChange={e=>setEndpoint(e.target.value)} placeholder="粘贴官方完整 HTTPS Endpoint"/><label>Model</label><input className="settings-input" value={model} onChange={e=>setModel(e.target.value)} placeholder="填写官方模型 ID"/><label>API Key</label><div className="secret-input"><input type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="输入 API Key"/></div><Button variant="secondary" onClick={saveAndTest} disabled={!endpoint||!model||!apiKey||status==="testing"}>{status==="success"?<><Check size={15}/>AI 连接成功</>:status==="testing"?"正在测试…":"保存并测试 AI"}</Button>{status==="error"&&<small className="field-error">{message}</small>}</div>}
export function Settings(){return <><PageHeader title="设置" subtitle="连接微信读书与 AI 服务。"/><div className="settings"><section className="settings-card"><div><h2>微信读书</h2><p>密钥会安全保存在系统凭据库中。</p></div><SecretField label="Agent Gateway API Key" kind="weread"/></section><section className="settings-card"><div><h2>AI Provider</h2><p>端点与模型以供应商官方控制台为准；ReadFlow 不会猜测或锁定版本。</p></div><AiSettings/></section><section className="settings-card"><div><h2>数据与隐私</h2><p>阅读记录保存在本机。AI 请求只发送问题和检索出的 Top‑20 笔记，API Key 不写入数据库或日志。</p></div><div className="privacy-badge"><Check size={16}/>本地优先</div></section></div></>}

